# Generated by Django 5.0.6 on 2024-09-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('pria', 'PRIA'), ('wanita', 'WANITA')], default='', max_length=20),
        ),
    ]
