# Generated by Django 5.0.6 on 2024-09-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('pria', 'PRIA'), ('wanita', 'WANITA')], default='pria', max_length=20),
        ),
    ]
