# Generated by Django 5.0.6 on 2024-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('kecelakaan_bencana', 'Kecelakaan & Bencana'), ('kesehatan_pendidikan', 'Kesehatan & Pendidikan'), ('panti_asuhan', 'Panti Asuhan')], max_length=50)),
                ('judul_donasi', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('jumlah_total_donasi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deskripsi', models.TextField()),
                ('status_donasi', models.CharField(choices=[('berlangsung', 'Berlangsung'), ('selesai', 'Selesai'), ('batal', 'Batal')], default='berlangsung', max_length=20)),
            ],
        ),
    ]
