# Generated by Django 5.0.6 on 2024-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_donation_delete_donasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
    ]
