# Generated by Django 5.0.6 on 2024-10-02 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_donation_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('change_description', models.TextField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='authentication.donation')),
            ],
        ),
    ]
